# link weights for the elements of the class Definition

PREFIX core: <https://www.foom.com/core#>

SELECT
  ?o1
  ?o2
  (COUNT(*) AS ?links)
WHERE {
  ?s a core:definition .
  {
    ?s core:defines ?o1, ?o2 .
  }
  UNION
  {
    ?s core:defines           ?o1 .
    ?o1 core:definition_refers_to ?o2 .
  }
  FILTER( STR(?o1) < STR(?o2) )
}
GROUP BY ?o1 ?o2
ORDER BY DESC(?links)

# SELECT
#     ?s ?o1 ?o2
# WHERE {
#     ?s  a <https://www.foom.com/core#definition> .
#     { ?s <https://www.foom.com/core#defines> ?o1, ?o2 .
#     FILTER ( STR(?o1) < STR(?o2) ) }
#     UNION
#     { ?s <https://www.foom.com/core#defines> ?o1 .
#      ?o1 <https://www.foom.com/core#definition_refers_to> ?o2 .
#     FILTER ( STR(?o1) < STR(?o2) ) }
# }
# ORDER BY ?s