# link weights for the elements of the class Definition

SELECT
    ?o
    (count (*) as ?links)
WHERE {
    ?s a <https://www.foom.com/core#definition> .
    { ?s <https://www.foom.com/core#defines> 
            / <https://www.foom.com/core#definition_refers_to> ?o . } 
    UNION
    { ?s <https://www.foom.com/core#defines> 
            / <https://www.foom.com/core#contains_concept> ?o . } 
}
group by ?o
order by desc(?links)