# link weights for the elements of the class Postulate

SELECT
    ?o1 ?o2
    (COUNT(*) AS ?pair_count)
WHERE {
    ?s a <https://www.foom.com/core#postulate> .
    { ?s <https://www.foom.com/core#refers_to> ?o1 , ?o2 . } # refers to
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#contains_concept> ?o1 , ?o2 . } # refers to / contains concept
    ######################
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_range> ?o1 , ?o2 . } # refers to / range
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_range>
            / <https://www.foom.com/core#contains_concept>  ?o1 , ?o2 . } # refers to / range / contains concept
    #####################
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_domain> ?o1 , ?o2 . } # refers to / domain
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_domain>
            / <https://www.foom.com/core#contains_concept>  ?o1 , ?o2 . } # refers to / domain / contains concept
    FILTER ( STR(?o1) < STR(?o2) ) 
}
GROUP BY ?o1 ?o2
ORDER BY DESC(?pair_count)


# SELECT
#     ?s ?o1 ?o2
# WHERE {
#     ?s a <https://www.foom.com/core#postulate> .
#     { ?s <https://www.foom.com/core#refers_to> ?o1 , ?o2 .
#       FILTER ( STR(?o1) < STR(?o2) ) } # refers to
#     union
#     { ?s <https://www.foom.com/core#refers_to> 
#             / <https://www.foom.com/core#contains_concept> ?o1 , ?o2 .
#       FILTER ( STR(?o1) < STR(?o2) ) } # refers to / contains concept
#     ######################
#     union
#     { ?s <https://www.foom.com/core#refers_to> 
#             / <https://www.foom.com/core#has_range> ?o1 , ?o2 .
#       FILTER ( STR(?o1) < STR(?o2) ) } # refers to / range
#     union
#     { ?s <https://www.foom.com/core#refers_to> 
#             / <https://www.foom.com/core#has_range>
#             / <https://www.foom.com/core#contains_concept>  ?o1 , ?o2 .
#       FILTER ( STR(?o1) < STR(?o2) ) } # refers to / range / contains concept
#     #####################
#     union
#     { ?s <https://www.foom.com/core#refers_to> 
#             / <https://www.foom.com/core#has_domain> ?o1 , ?o2 .
#       FILTER ( STR(?o1) < STR(?o2) ) } # refers to / domain
#     union
#     { ?s <https://www.foom.com/core#refers_to> 
#             / <https://www.foom.com/core#has_domain>
#             / <https://www.foom.com/core#contains_concept>  ?o1 , ?o2 .
#       FILTER ( STR(?o1) < STR(?o2) ) } # refers to / domain / contains concept
# }
# ORDER BY ?s
