# link weights for the elements of the class Postulate

SELECT
    ?s ?o
    (count (*) as ?links)
WHERE {
    ?s a <https://www.foom.com/core#postulate> .
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#contains_concept> 
            / <https://www.foom.com/core#contains_concept> ?o . } # refers to / contains concept / contains concept
    UNION
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#contains_concept> 
            / <https://www.foom.com/core#definition_refers_to> ?o . } # refers to / contains concept / contains concept
    ######################
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_range> ?o . } # refers to / range
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_range>
            / <https://www.foom.com/core#contains_concept>
            / <https://www.foom.com/core#contains_concept>  ?o . } # refers to / range / contains concept / super-concept
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_range>
            / <https://www.foom.com/core#contains_concept>
            / <https://www.foom.com/core#definition_refers_to>  ?o . } # refers to / range / contains concept / super-concept
    #####################
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_domain>
            / <https://www.foom.com/core#contains_concept>
            / <https://www.foom.com/core#contains_concept>  ?o . } # refers to / domain / contains concept / super-concept
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_domain>
            / <https://www.foom.com/core#contains_concept>
            / <https://www.foom.com/core#definition_refers_to>  ?o . } # refers to / range / contains concept / super-concept
}
group by ?s ?o
order by ?s desc(?links) 