# link weights for the elements of the class Proposition
# only hierarchical items

SELECT
    ?s ?o
    (count (*) as ?links)
WHERE {
    ?s a <https://www.foom.com/core#proposition> .
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#contains_concept> 
            / <https://www.foom.com/core#is_sub_concept_of> ?o . } # refers to / contains concept / super-concept
    ######################
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_range>
            / <https://www.foom.com/core#contains_concept>
            / <https://www.foom.com/core#is_sub_concept_of>  ?o . } # refers to / range / contains concept / super-concept
    #####################
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_domain>
            / <https://www.foom.com/core#contains_concept>
            / <https://www.foom.com/core#is_sub_concept_of>  ?o . } # refers to / domain / contains concept / super-concept
    #########################
    union
    { ?s <https://www.foom.com/core#refers_to>
            / <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#contains_concept> 
            / <https://www.foom.com/core#is_sub_concept_of> ?o . } # refers to [2] / contains concept / super-concept
    ####################################
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_range>
            / <https://www.foom.com/core#contains_concept>
            / <https://www.foom.com/core#is_sub_concept_of>  ?o . } # refers to [2] / range / contains concept / super-concept
    #####################
    union
    { ?s <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#refers_to> 
            / <https://www.foom.com/core#has_domain>
            / <https://www.foom.com/core#contains_concept>
            / <https://www.foom.com/core#is_sub_concept_of>  ?o . } # refers to [2] / domain / contains concept / super-concept
    #########################
}
group by ?s ?o
order by ?s desc(?links) 