# link weights for the elements of the class Definition
# without hierarchical imports

SELECT
    ?s ?o
    (count (*) as ?links)
WHERE {
    ?s a <https://www.foom.com/core#definition> .
    ?s <https://www.foom.com/core#defines> ?o .
}
group by ?s ?o
order by ?s desc(?links) 