# extract concepts directly related to a proof

prefix : <https://www.foom.com/core#>

select distinct
    ?item_iri
    ?concept_label
where {
    ?item_iri
        a :proof ;
        :contains_concept ?concept_iri .
    ?concept_iri 
        rdfs:label ?concept_label .
}
order by ?item_iri