# find concepts related to a proposition

prefix : <https://www.foom.com/core#>

select distinct
    ?item_iri
    ?concept_label
where {
    ?item_iri
        a :proposition ;
        :contains_concept ?concept_iri .
    ?concept_iri
        rdfs:label  ?concept_label .
}
order by ?item_iri