graph TD

    A(concept of 
        side of a triangle) -->|is sub-concept of| B(concept of 
            side)

    A -->|is concept of a| C(diagrammatic object)
    
    B -->|is sub-concept of| D(concept 
        of finite-straight-line)
    
    A -->|has conceptual component| E(concept of 
        triangle)
    
    A -->|is a| F(concept)
    
    A -->|is-super-concept-of| G(concept of base 
        of a triangle)
    
    A -->|is concept in| H(relation instance: 
        finite-straight-line = side-of-trianle)

    B -->|is concept of a| C

    D -->|is concept of a| C
